# Step 1: Modules caching
FROM golang as modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux \
    go build -tags migrate -o /bin/app ./cmd/proxy

# Step 3: Final
FROM scratch

EXPOSE 5000

# GOPATH for scratch images is /
COPY --from=builder /app/cmd/proxy/config.yml /
COPY --from=builder /bin/app /app
CMD ["/app"]